variable "region" {}
variable "gcp_project" {}
variable "credentials" {}
variable "name" {}
variable "subnet_cidr1" {}
variable "subnet_cidr2" {}
variable "subnet_cidr3" {}
variable "subnet_cidr4" {}
variable "myip" {}
variable "network1-instname" {}
variable "network2-instname"  {}
variable "vmtype" {}
variable "image" {}
variable "sa-email" {}
variable "disk_size" {}
variable "gke_node_type" {}
variable "node_disk_size" {}
variable "node_disk_type" {}
variable "node_min_count" {}
variable "node_max_count" {}
variable "master_ip_range" {}
variable "db_tier" {}
